# Generated by Django 5.2.4 on 2025-08-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('empresa_proyecto', models.CharField(max_length=250, verbose_name='Empresa / Proyecto')),
                ('servicio', models.CharField(choices=[('branding', 'Branding & Identidad'), ('web', 'Desarrollo Web'), ('marketing', 'Marketing Digital'), ('content', 'Creación de Contenido'), ('all', 'Proyecto integral')], max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
